# Generated by Django 3.0.5 on 2020-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcode',
            name='offer_percent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
